### ISSUE TITLE
Cross Scripting Security Vulnerability - Checkmarx

### ISSUE THREAD

**Issue by prgoodwin** [cloudfoundry-community/go-uaa#56]
Checkmarx Security scan has caught a high priority security vulnerability in uaa_transport.go  

From the report:
The application's func embeds untrusted data in the generated output with Printf, at line 42 of
server/uaa/uaa_transport.go. This untrusted data is embedded straight into the output without proper sanitization or
encoding, enabling an attacker to inject malicious code into the output.
The attacker would be able to alter the output data by simply sending modified values in the user input Header, which is
read by the func method at line 15 of server/uaa/uaa_transport.go. This input then flows through the code, and written to
the console or STDOUT, without sanitization. In some scenarios, this output will also be sent back to the user's browser.
This can enable a Reflected Cross-Site Scripting (XSS) attack if the code's console output is used by the application as
part of a web-page, as often occurs with CGI scripts.

What is the proper way to sanitize this logging printf?

**Comment by joefitzgerald** [comment]
I'm not sure I share the same interpretation of the way the code works here. 

There isn't a scenario where the Printf invocation in logResponse can access or mutate the response. Therefore, there is no XSS issue (that wouldn't be present in the go standard library) because the response is provably unmodified in all code paths.
